### ISSUE TITLE
Error : trajans-tanks-forge-1.19.4-2.4

### ISSUE THREAD

**Issue by Skytoone** [Crescentine/Trajans-Core#9]
Hello, I have an error in my console:
Version: 1.19.3
Platform: ArcLight-1.0.6

[00:38:23 ERROR]: Couldn't parse loot table trajanstanks:entities/artillery_entity_type
com.google.gson.JsonSyntaxException: Expected name to be an item, was unknown string 'trajanstanks:artillery_item'
at net.minecraft.util.GsonHelper.m_13866_(GsonHelper.java:137) ~[server-1.19.4-20230314.122934-srg.jar%23173!/:?]
at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
at net.minecraft.util.GsonHelper.m_13874_(GsonHelper.java:137) ~[server-1.19.4-20230314.122934-srg.jar%23173!/:?]
at net.minecraft.util.GsonHelper.m_13909_(GsonHelper.java:145) ~[server-1.19.4-20230314.122934-srg.jar%23173!/:?]
at net.minecraft.world.level.storage.loot.entries.LootItem$Serializer.m_7267_(LootItem.java:55) ~[server-1.19.4-20230314.122934-srg.jar%23173!/:?]
at net.minecraft.world.level.storage.loot.entries.LootItem$Serializer.m_7267_(LootItem.java:40) ~[server-1.19.4-20230314.122934-srg.jar%23173!/:?]
at net.minecraft.world.level.storage.loot.entries.LootPoolSingletonContainer$Serializer.m_5921_(LootPoolSingletonContainer.java:151) ~[server-1.19.4-20230314.122934-srg.jar%23173!/:?]
at net.minecraft.world.level.storage.loot.entries.LootPoolSingletonContainer$Serializer.m_5921_(LootPoolSingletonContainer.java:129) ~[server-1.19.4-20230314.122934-srg.jar%23173!/:?]
at net.minecraft.world.level.storage.loot.entries.LootPoolEntryContainer$Serializer.m_7561_(LootEntry_SerializerMixin.java:86) ~[server-1.19.4-20230314.122934-srg.jar%23173!/:?]
at net.minecraft.world.level.storage.loot.entries.LootPoolEntryContainer$Serializer.m_7561_(LootEntry_SerializerMixin.java:74) ~[server-1.19.4-20230314.122934-srg.jar%23173!/:?]
at net.minecraft.world.level.storage.loot.GsonAdapterFactory$JsonAdapter.deserialize(GsonAdapterFactory.java:102) ~[server-1.19.4-20230314.122934-srg.jar%23173!/:?]
at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[gson-2.10.jar%23104!/:?]
at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40) ~[gson-2.10.jar%23104!/:?]
at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[gson-2.10.jar%23104!/:?]
at com.google.gson.Gson.fromJson(Gson.java:1214) ~[gson-2.10.jar%23104!/:?]
at com.google.gson.Gson.fromJson(Gson.java:1319) ~[gson-2.10.jar%23104!/:?]
at com.google.gson.Gson.fromJson(Gson.java:1290) ~[gson-2.10.jar%23104!/:?]
at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:179) ~[gson-2.10.jar%23104!/:?]
at net.minecraft.util.GsonHelper.m_13808_(GsonHelper.java:455) ~[server-1.19.4-20230314.122934-srg.jar%23173!/:?]
at net.minecraft.util.GsonHelper.m_13836_(GsonHelper.java:463) ~[server-1.19.4-20230314.122934-srg.jar%23173!/:?]
at net.minecraft.world.level.storage.loot.LootPool$Serializer.deserialize(LootPool.java:190) ~[server-1.19.4-20230314.122934-srg.jar%23173!/:?]
at net.minecraft.world.level.storage.loot.LootPool$Serializer.deserialize(LootPool.java:187) ~[server-1.19.4-20230314.122934-srg.jar%23173!/:?]
at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[gson-2.10.jar%23104!/:?]
at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40) ~[gson-2.10.jar%23104!/:?]
at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[gson-2.10.jar%23104!/:?]
at com.google.gson.Gson.fromJson(Gson.java:1214) ~[gson-2.10.jar%23104!/:?]
at com.google.gson.Gson.fromJson(Gson.java:1319) ~[gson-2.10.jar%23104!/:?]
at com.google.gson.Gson.fromJson(Gson.java:1290) ~[gson-2.10.jar%23104!/:?]
at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:179) ~[gson-2.10.jar%23104!/:?]
at net.minecraft.util.GsonHelper.m_13808_(GsonHelper.java:455) ~[server-1.19.4-20230314.122934-srg.jar%23173!/:?]
at net.minecraft.util.GsonHelper.m_13845_(GsonHelper.java:473) ~[server-1.19.4-20230314.122934-srg.jar%23173!/:?]
at net.minecraft.world.level.storage.loot.LootTable$Serializer.deserialize(LootTable.java:258) ~[server-1.19.4-20230314.122934-srg.jar%23173!/:?]
at net.minecraft.world.level.storage.loot.LootTable$Serializer.deserialize(LootTable.java:255) ~[server-1.19.4-20230314.122934-srg.jar%23173!/:?]
at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[gson-2.10.jar%23104!/:?]
at com.google.gson.Gson.fromJson(Gson.java:1214) ~[gson-2.10.jar%23104!/:?]
at com.google.gson.Gson.fromJson(Gson.java:1319) ~[gson-2.10.jar%23104!/:?]
at com.google.gson.Gson.fromJson(Gson.java:1261) ~[gson-2.10.jar%23104!/:?]
at net.minecraftforge.common.ForgeHooks.loadLootTable(ForgeHooksMixin.java:832) ~[forge-1.19.4-45.2.6-universal.jar%23178!/:?]
at net.minecraft.world.level.storage.loot.LootTables.lambda$apply$0(LootTableManagerMixin.java:41) ~[server-1.19.4-20230314.122934-srg.jar%23173!/:?]
at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
at net.minecraft.world.level.storage.loot.LootTables.m_5787_(LootTableManagerMixin.java:38) ~[server-1.19.4-20230314.122934-srg.jar%23173!/:?]
at net.minecraft.world.level.storage.loot.LootTables.m_5787_(LootTableManagerMixin.java:16) ~[server-1.19.4-20230314.122934-srg.jar%23173!/:?]
at net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10789_(SimplePreparableReloadListener.java:13) ~[server-1.19.4-20230314.122934-srg.jar%23173!/:?]
at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
at net.minecraft.server.packs.resources.SimpleReloadInstance.m_143940_(SimpleReloadInstance.java:69) ~[server-1.19.4-20230314.122934-srg.jar%23173!/:?]
at net.minecraft.Util.m_214652_(Util.java:770) ~[server-1.19.4-20230314.122934-srg.jar%23173!/:?]
at net.minecraft.Util.m_214679_(Util.java:759) ~[server-1.19.4-20230314.122934-srg.jar%23173!/:?]
at net.minecraft.server.Main.main(Main.java:166) ~[server-1.19.4-20230314.122934-srg.jar%23173!/:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:29) ~[fmlloader-1.19.4-45.2.6.jar%23101!/:?]
at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.8.jar%2388!/:?]
at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.8.jar%2388!/:?]
at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.8.jar%2388!/:?]
at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) ~[modlauncher-10.0.8.jar%2388!/:?]
at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) ~[modlauncher-10.0.8.jar%2388!/:?]
at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.8.jar%2388!/:?]
at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.8.jar%2388!/:?]
at io.izzel.arclight.boot.application.ApplicationBootstrap.accept(ApplicationBootstrap.java:41) ~[arclight-forge-1.19.4-1.0.6.jar:arclight-1.19.4-1.0.6-0437196]
at io.izzel.arclight.boot.application.ApplicationBootstrap.accept(ApplicationBootstrap.java:12) ~[arclight-forge-1.19.4-1.0.6.jar:arclight-1.19.4-1.0.6-0437196]
at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
at io.izzel.arclight.boot.application.Main_Forge.main(Main_Forge.java:23) ~[arclight-forge-1.19.4-1.0.6.jar%2382!/:arclight-1.19.4-1.0.6-0437196]
at io.izzel.arclight.server.Launcher.main(Launcher.java:18) ~[arclight-forge-1.19.4-1.0.6.jar%2382!/:arclight-1.19.4-1.0.6-0437196]
[00:38:24 ERROR]: Parsing error loading custom advancement trajanstanks:assembly/panzer2: Expected item to be an item, was unknown string 'trajanstanks:tank_item'
[00:38:24 ERROR]: Parsing error loading custom advancement trajanstanks:assembly/tiger: Expected item to be an item, was unknown string 'trajanstanks:heavy_tank_item'
[00:38:24 ERROR]: Parsing error loading custom advancement trajanstanks:assembly/t34: Expected item to be an item, was unknown string 'trajanstanks:medium_tank_item'
[00:38:24 ERROR]: Parsing error loading custom advancement trajanstanks:assembly/start: Expected item to be an item, was unknown string 'trajanstanks:crafter_block'
[00:38:24 ERROR]: Couldn't load advancement trajanstanks:assembly/cruisermk1: Task Advancement{parentId=trajanstanks:assembly/start, display=net.minecraft.advancements.DisplayInfo@35747e72, rewards=AdvancementRewards{experience=0, loot=[], recipes=[], function=net.minecraft.commands.CommandFunction$CacheableFunction@71fdb621}, criteria={requirement=net.minecraft.advancements.Criterion@1be39048}, requirements=[[requirement]]}

**Comment by hisRoyalty** [comment]
Unfortunately we do not support previous versions such as 1.19.4 as of yet, but we do plan on backporting soon. Please check if this issue persists in the latest version of Trajan's Core and Trajan's Tanks. Also, we do not really support the platform Arclight.

Although the platform shouldn't really be an issue, we would need to know how you replicate this problem so we can solve it. (i.e. what you need to do for this error to occur).

Thanks.
- hisroyalty

**Comment by Skytoone** [comment]
Sorry I'm in 1.19.4 not 1.19.3
